### ISSUE TITLE
howto add BLEFlora and BLEMija

### ISSUE THREAD

**Issue by mod25** [enesbcs/ESPEasyRetro#1]
i have issue to add P103 P104 to normal esp easy source can you assist howto compile i get issue with to big for my esp32
best,
mod25

**Comment by enesbcs** [comment]
I do not think that it is possible.
It is designed to work only with this ESPEasyRetro build. Newer ESPEasy builds are insanely large. BLE stack is very large for ESP32.

**Comment by mod25** [comment]
Can you let me know howto compile ESPEasyRetro with vscode. Or so I need to have arduino IDE? I have compiled with atom and platformio on Mac as described on ESPEasy Mega.
Thank you very much

**Comment by enesbcs** [comment]
Sorry i've never used vscode.
A precompiled binary is available for ESP32 made with Arduino IDE.
https://github.com/enesbcs/ESPEasyRetro/tree/master/bin

**Comment by mod25** [comment]
already tried with precompiled binary.
result:
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0010,len:4
load:0x3fff0014,len:812
load:0x40078000,len:0
load:0x40078000,len:10164
entry 0x400789f8
user code done

after now 3 hours of getting libs for compiling espeasyretro giving up today maybe you know better ways to get it on my wemos d1 mini32
thank you

**Comment by enesbcs** [comment]
Libraries are included in this ESPEasy release:
https://github.com/letscontrolit/ESPEasy/archive/mega-20180826.zip

**Comment by mod25** [comment]
sorry but there is more missing 
fatal error: src/Globals/Nodes.h: No such file or directory

may you be able to pack sources new?
thanky ou

**Comment by enesbcs** [comment]
I do not know what do you compiling, there are no reference to "Nodes.h" in my ESPEasyRetro... the ZIP file above only linked for its libraries.

**Comment by enesbcs** [comment]
Project is now abandoned in favor of mPyEasy
https://github.com/enesbcs/mpyeasy
